# -*- coding: utf-8 -*-
"""Aula07-jogodeacerto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hUlGqw1o3OPI7RxGrt_8qVjJ7pmIweKe
"""

#for para  e while enquanto


# c = 1

# while c<=10 :
#   print("contador",c)

#   c =

# Random - gera um numero aleatorio
# import random
# numero_aleatorio = random.random()
# print(numero_aleatorio)

# randint - gera um numero aleatorio inteiro
# numero_aleatorio02 = random.randint(0,25)

# print(numero_aleatorio02)

import random

chute = input("digite um numero entre 12 e 24")
numero_aleatorio = random.randint(12,25)
chances = 3

while chances <=3:
 chute = int(input("digitar um número entre 12 e 24: "))
 numero_aleatorio = random.randint(1,2)

 if  chute == numero_aleatorio:
    print(f"você acertou, o numero é{numero_aleatorio}")
    break

 if chute!= numero_aleatorio:
      chances = chances -1
      print(f"você errou, o numero é{numero_aleatorio}, só tem{chances}, chances")
      chute = input("dgitar um numero entre 12 e 24")
 if chances == 0:
      print("Você esgotou sua chances")
      break